In [43]:
import pandas as pd
import numpy as np
df = pd.read_csv('handle_Attack_data/TOTAL_preprocessing_43.csv')
df.head()

0         1         2         3         4         5         6  \
0  0.000809  4.927139  2.332438  0.001884  0.018925  0.000000  0.053959   
1  0.000809  2.294466  2.136721  0.001541  0.015484  0.000000  0.034291   
2  0.000809  4.922866  2.492760  0.001755  0.017634  0.000000  0.078164   
3  0.913570  1.934498  0.000000  0.000000  0.000000  0.000000  0.000000   
4  0.006760  5.972557  4.760513  0.016824  0.000000  1.954473  0.000000   

          7         8         9  ...        34        35        36        37  \
0  3.552994  1.684010  4.450028  ...  2.332438  0.000000  0.000000  0.301030   
1  6.025808  4.309825  1.821732  ...  2.136721  0.000000  0.000000  0.301030   
2  3.670518  1.688196  4.445755  ...  2.492760  0.000000  0.000000  0.301030   
3  0.000000  4.371630  1.934498  ...  0.000000  0.001923  0.508194  0.000000   
4  4.794249  1.805151  4.209156  ...  4.760513  0.125015  0.000961  1.380211   

         38   39   40   41   42  43  
0  0.344086  0.0  0.0  0.0  0.0   0  
1  0.215054  0.0  0.0  0.0  0.0   0  
2  0.344086  0.0  0.0  0.0  0.0   0  
3  0.344086  0.0  0.0  0.0  0.0   0  
4  0.215054  0.0  0.0  0.0  0.0   0  

[5 rows x 44 columns]

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 832191 entries, 0 to 832190
Data columns (total 44 columns):
0     832191 non-null float64
1     832191 non-null float64
2     832191 non-null float64
3     832191 non-null float64
4     832191 non-null float64
5     832191 non-null float64
6     832191 non-null float64
7     832191 non-null float64
8     832191 non-null float64
9     832191 non-null float64
10    832191 non-null float64
11    832191 non-null float64
12    832191 non-null float64
13    832191 non-null float64
14    832191 non-null float64
15    832191 non-null float64
16    832191 non-null float64
17    832191 non-null float64
18    832191 non-null float64
19    832191 non-null float64
20    832191 non-null float64
21    832191 non-null float64
22    832191 non-null float64
23    832191 non-null float64
24    832191 non-null int64
25    832191 non-null float64
26    832191 non-null float64
27    832191 non-null float64
28    832191 non-null float64
29    832191 non-null

In [45]:
df.shape

(832191, 44)

In [59]:

features = df[:,0:43]
labels = df[:,43]
features.shape

(832191, 43)

In [60]:
labels.shape

(832191,)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

X_train, X_test, y_train, y_test = train_test_split(df['Consumer_complaint_narrative'], df['Product'], random_state = 0)
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train)
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

clf = MultinomialNB().fit(X_train_tfidf, y_train)

In [61]:
labels.shape

(832191,)

In [50]:
np.isinf(labels)

array([False, False, False, ..., False, False, False])

In [51]:
np.isnan(labels)

array([False, False, False, ..., False, False, False])

In [52]:
np.isinf(features)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [53]:
np.isnan(features)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [62]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

from sklearn.model_selection import cross_val_score

models = [
    RandomForestClassifier(n_estimators=200, max_depth=3, random_state=0),
    LinearSVC(),
    MultinomialNB(),
    LogisticRegression(random_state=0),
]
CV = 5
cv_df = pd.DataFrame(index=range(CV * len(models)))
entries = []
for model in models:
  model_name = model.__class__.__name__
  accuracies = cross_val_score(model, features, labels, scoring='accuracy', cv=CV)
  for fold_idx, accuracy in enumerate(accuracies):
    entries.append((model_name, fold_idx, accuracy))
cv_df = pd.DataFrame(entries, columns=['model_name', 'fold_idx', 'accuracy'])

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [63]:
import seaborn as sns

sns.boxplot(x='model_name', y='accuracy', data=cv_df)
sns.stripplot(x='model_name', y='accuracy', data=cv_df, 
              size=8, jitter=True, edgecolor="gray", linewidth=2)
plt.show()

ModuleNotFoundError: No module named 'seaborn'

In [64]:
cv_df.groupby('model_name').accuracy.mean()

model_name
LinearSVC                 0.622004
LogisticRegression        0.509280
MultinomialNB             0.270343
RandomForestClassifier    0.885498
Name: accuracy, dtype: float64